### ISSUE TITLE
Capture 'unavailable' values

### ISSUE THREAD

**Issue by SeLLeRoNe** [finity69x2/toggle-control-button-row#1]
Hi there,
first of all, thanks for this card, very nice 👍 

I have implemented it in my UI and I noticed that a switch which is on an 'unavailable' state is being showed as ON but with the "off" color:
![image](https://user-images.githubusercontent.com/9599441/103526033-80494d00-4e80-11eb-979c-c2123d0cdba0.png)

So I was wondering, can this be implemented?:
1 - Change ON/OFF to N/A for unavailable entities
2 - Have the ability to set a color for those (and maybe have a default color background of gray for when a specific one is not set.

Hope it makes sense :)

Thanks
Andrea

**Comment by finity69x2** [comment]
i'll look into it.

**Comment by finity69x2** [comment]
I just made some changes to the code for this. And I created a dev branch for the first time ever (so hopefully it works...)

Could you possibly try to install the code from the dev branch and test it for me to see if it works the way you want?

**Comment by SeLLeRoNe** [comment]
Hi there,
I can see the change:
![image](https://user-images.githubusercontent.com/9599441/103776229-6dc14600-502f-11eb-9599-a253926757e6.png)

But I would change the text from unav to N/A, I think it looks better.
The text is not really readable not sure if it's a combination of background/text color, maybe the background should be little darker?

I haven't tested selecting a specific color since I don't know what the option would be.

Beside, thanks a lot for doing this! :)

A

**Comment by finity69x2** [comment]
I agree with you on the text so I changed it to N/A.

I think I'll leave the color as is for now. I tried to make it similar to the normal unavailable color so it's obvious that it's unavailable. I also didn't make that color or text configurable. But I might later. I'll have to think about it.

**Comment by SeLLeRoNe** [comment]
Well for the color I am not 100% convinced, are you using a pre-defined color or are you getting it from the theme?

I think that have it configurable would be a nice add :)

Despite that, thanks!
