### ISSUE TITLE
Problems after version update 2022.3.1

### ISSUE THREAD

**Issue by mirko76to** [finity69x2/toggle-control-button-row#3]
After the update, the buttons appear to me with the writing "N / A", some return to normal after the entity has changed state, others do not.

![image](https://user-images.githubusercontent.com/56404646/156887609-ed276860-ded5-4fff-b080-1a1c7ac7e605.png)

![image](https://user-images.githubusercontent.com/56404646/156887638-b561a3d9-d36d-4144-b3e0-b5626190536b.png)

Thank you

**Comment by finity69x2** [comment]
can you show an example plugin config for the entities that don't work.

what is the state of the entities when they show N/A?
